/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as NewRouteImport } from './routes/new'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as IntegrationsCliRouteImport } from './routes/integrations_.cli'
import { Route as IntegrationsSlackRouteImport } from './routes/integrations_.slack'
import { Route as SIdRouteImport } from './routes/s.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsCliRoute = IntegrationsCliRouteImport.update({
  id: '/integrations_/cli',
  path: '/integrations/cli',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsSlackRoute = IntegrationsSlackRouteImport.update({
  id: '/integrations_/slack',
  path: '/integrations/slack',
  getParentRoute: () => rootRouteImport,
} as any)
const SIdRoute = SIdRouteImport.update({
  id: '/s/$id',
  path: '/s/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/integrations': typeof IntegrationsRoute
  '/new': typeof NewRoute
  '/security': typeof SecurityRoute
  '/integrations/cli': typeof IntegrationsCliRoute
  '/integrations/slack': typeof IntegrationsSlackRoute
  '/s/$id': typeof SIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/integrations': typeof IntegrationsRoute
  '/new': typeof NewRoute
  '/security': typeof SecurityRoute
  '/integrations/cli': typeof IntegrationsCliRoute
  '/integrations/slack': typeof IntegrationsSlackRoute
  '/s/$id': typeof SIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/integrations': typeof IntegrationsRoute
  '/new': typeof NewRoute
  '/security': typeof SecurityRoute
  '/integrations_/cli': typeof IntegrationsCliRoute
  '/integrations_/slack': typeof IntegrationsSlackRoute
  '/s/$id': typeof SIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/integrations'
    | '/new'
    | '/security'
    | '/integrations/cli'
    | '/integrations/slack'
    | '/s/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/integrations'
    | '/new'
    | '/security'
    | '/integrations/cli'
    | '/integrations/slack'
    | '/s/$id'
  id:
    | '__root__'
    | '/'
    | '/integrations'
    | '/new'
    | '/security'
    | '/integrations_/cli'
    | '/integrations_/slack'
    | '/s/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IntegrationsRoute: typeof IntegrationsRoute
  NewRoute: typeof NewRoute
  SecurityRoute: typeof SecurityRoute
  IntegrationsCliRoute: typeof IntegrationsCliRoute
  IntegrationsSlackRoute: typeof IntegrationsSlackRoute
  SIdRoute: typeof SIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations_/cli': {
      id: '/integrations_/cli'
      path: '/integrations/cli'
      fullPath: '/integrations/cli'
      preLoaderRoute: typeof IntegrationsCliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations_/slack': {
      id: '/integrations_/slack'
      path: '/integrations/slack'
      fullPath: '/integrations/slack'
      preLoaderRoute: typeof IntegrationsSlackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$id': {
      id: '/s/$id'
      path: '/s/$id'
      fullPath: '/s/$id'
      preLoaderRoute: typeof SIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IntegrationsRoute: IntegrationsRoute,
  NewRoute: NewRoute,
  SecurityRoute: SecurityRoute,
  IntegrationsCliRoute: IntegrationsCliRoute,
  IntegrationsSlackRoute: IntegrationsSlackRoute,
  SIdRoute: SIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
